application: isumm-canary
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /static
  static_dir: static
  application_readable: true


- url: /app
  script: _go_app
  login: required

- url: /app/ops
  script: _go_app
  login: required

- url: /inv
  script: _go_app
  login: required

- url: /op
  script: _go_app
  login: required
